export const routes = {
  main: { name: 'Главная', path: '/' },
  login: { name: 'Вход', path: '/login' },
  signup: { name: 'Регистрация', path: '/signup' },
  myCars: { name: 'Мои автомобили', path: '/my-cars' },
  allExchangedCarsScreen: { name: 'Автомобили на обмен', path: '/exchange-cars' },
  carsCreate: { name: 'Добавить авто', path: '/add-car' },
  aboutCar: { name: 'Об автомобиле', path: '/about-car' },
  verify: { name: 'Активировать аккаунт', path: '/verify' },
  profile: { name: 'Профиль', path: '/profile' },
  rentCars: { name: 'Машины в аренду', path: '/rent-car' },
  rentList: { name: 'Список аренды', path: '/rent-list' },
  likes: { name: 'Лайки', path: '/likes' },
  feedback: { name: 'Отзыв', path: '/feedback' },
  history: { name: 'История', path: '/history' },
};
